In [9]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from statsmodels.miscmodels.ordinal_model import OrderedModel
from sklearn.metrics import mean_absolute_error
import numpy as np

In [2]:
df = pd.read_csv("./data/df_final_janeiro_18.csv")
df

,Autoavaliacao_Saude,Idade,Sexo,Cor_Raca,Estado_Civil,Nivel_Instrucao,Total_Moradores,Qtd_Comodos,Qtd_Banheiros,Possui_Automovel,...,Diagnostico_Doenca_Cronica,Grau_Limite_Depressao,Grau_Limite_Doenca_Mental,Grau_Limite_DORT,Pratica_Exercicio,Horas_TV,Fuma,Freq_Alcool,Apoio_Familiar,Apoio_Amigos
0,3.0,55.0,2.0,1.0,1.0,1.0,6.0,5.0,2.0,2.0,...,1.0,2.0,2.0,1.0,1.0,3.0,3.0,2.0,3.0,0.0
1,2.0,19.0,2.0,4.0,4.0,1.0,4.0,4.0,1.0,2.0,...,2.0,2.0,2.0,2.0,2.0,6.0,1.0,2.0,3.0,2.0
2,3.0,45.0,2.0,2.0,4.0,1.0,8.0,8.0,4.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,1.0,1.0
3,3.0,58.0,2.0,2.0,3.0,1.0,1.0,1.0,0.0,2.0,...,2.0,2.0,2.0,2.0,1.0,1.0,3.0,1.0,1.0,0.0
4,2.0,28.0,2.0,4.0,4.0,2.0,2.0,2.0,1.0,2.0,...,2.0,2.0,2.0,2.0,1.0,2.0,3.0,1.0,3.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90841,3.0,54.0,2.0,4.0,1.0,1.0,3.0,5.0,1.0,1.0,...,1.0,2.0,2.0,2.0,2.0,3.0,1.0,3.0,3.0,3.0
90842,2.0,44.0,1.0,4.0,2.0,1.0,2.0,5.0,1.0,1.0,...,2.0,2.0,2.0,2.0,2.0,6.0,1.0,3.0,2.0,2.0
90843,2.0,32.0,2.0,4.0,1.0,2.0,4.0,4.0,1.0,2.0,...,2.0,2.0,2.0,2.0,1.0,4.0,3.0,1.0,3.0,0.0
90844,3.0,54.0,1.0,4.0,1.0,1.0,3.0,10.0,3.0,1.0,...,1.0,1.0,2.0,1.0,1.0,2.0,3.0,1.0,1.0,3.0
90845,3.0,32.0,1.0,1.0,4.0,1.0,1.0,5.0,1.0,1.0,...,2.0,2.0,2.0,2.0,1.0,3.0,3.0,3.0,3.0,2.0

In [3]:
target = "Autoavaliacao_Saude"

In [6]:
# Splitando a variavel em X e Y
y = df[target]
X = df.drop(columns=[target])

scaler = StandardScaler()
X_scaled = pd.DataFrame(
    scaler.fit_transform(X),
    columns=X.columns,
    index=X.index
)


model = OrderedModel(
    y,
    X_scaled,
    distr="logit" # "probit"
)

result = model.fit(method="bfgs")

print(result.summary())

Optimization terminated successfully.
         Current function value: 1.015671
         Iterations: 26
         Function evaluations: 27
         Gradient evaluations: 27
                              OrderedModel Results
===============================================================================
Dep. Variable:     Autoavaliacao_Saude   Log-Likelihood:                -92270.
Model:                    OrderedModel   AIC:                         1.846e+05
Method:             Maximum Likelihood   BIC:                         1.849e+05
Date:                 Wed, 21 Jan 2026
Time:                         22:54:36
No. Observations:                90846
Df Residuals:                    90817
Df Model:                           25
==============================================================================================
                                 coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------------
Idade                          0.3695      0.009     41.209      0.000       0.352       0.387
Sexo                          -0.0976      0.007    -13.743      0.000      -0.112      -0.084
Cor_Raca                       0.1299      0.007     19.012      0.000       0.117       0.143
Estado_Civil                  -0.0170      0.007     -2.364      0.018      -0.031      -0.003
Nivel_Instrucao                0.1288      0.007     17.263      0.000       0.114       0.143
Total_Moradores                0.1565      0.007     21.487      0.000       0.142       0.171
Qtd_Comodos                   -0.0467      0.010     -4.856      0.000      -0.065      -0.028
Qtd_Banheiros                 -0.1326      0.010    -13.715      0.000      -0.152      -0.114
Possui_Automovel               0.1414      0.008     18.311      0.000       0.126       0.157
Possui_Computador              0.2219      0.008     28.088      0.000       0.206       0.237
Acesso_Internet                0.1027      0.008     13.674      0.000       0.088       0.117
Freq_Problemas_Sono            0.1609      0.008     20.329      0.000       0.145       0.176
Freq_Cansaco                   0.2654      0.009     30.358      0.000       0.248       0.283
Freq_Anedonia                  0.1397      0.009     15.759      0.000       0.122       0.157
Freq_Depressao                 0.2339      0.008     27.608      0.000       0.217       0.251
Diagnostico_Doenca_Cronica    -0.4462      0.008    -56.015      0.000      -0.462      -0.431
Grau_Limite_Depressao         -0.0163      0.007     -2.317      0.020      -0.030      -0.003
Grau_Limite_Doenca_Mental     -0.0356      0.007     -5.399      0.000      -0.048      -0.023
Grau_Limite_DORT               0.0001      0.007      0.020      0.984      -0.014       0.015
Pratica_Exercicio              0.2093      0.007     29.800      0.000       0.195       0.223
Horas_TV                      -0.0058      0.007     -0.870      0.384      -0.019       0.007
Fuma                          -0.0199      0.007     -2.929      0.003      -0.033      -0.007
Freq_Alcool                   -0.1588      0.007    -22.057      0.000      -0.173      -0.145
Apoio_Familiar                -0.0304      0.007     -4.364      0.000      -0.044      -0.017
Apoio_Amigos                  -0.0890      0.007    -12.691      0.000      -0.103      -0.075
1.0/2.0                       -2.4030      0.011   -210.112      0.000      -2.425      -2.381
2.0/3.0                        1.1070      0.004    254.007      0.000       1.099       1.116
3.0/4.0                        0.9863      0.006    170.286      0.000       0.975       0.998
4.0/5.0                        0.6373      0.015     43.028      0.000       0.608       0.666
==============================================================================================

In [8]:
coef = pd.DataFrame({
    "coef": result.params[:len(X.columns)],
    "p_value": result.pvalues[:len(X.columns)]
}, index=X.columns)

coef["odds_ratio"] = coef["coef"].apply(lambda x: np.exp(x))
coef = coef.sort_values("coef")
coef

                                coef        p_value  odds_ratio
Diagnostico_Doenca_Cronica -0.446226   0.000000e+00    0.640039
Freq_Alcool                -0.158757  8.229106e-108    0.853204
Qtd_Banheiros              -0.132611   8.238793e-43    0.875805
Sexo                       -0.097605   5.627869e-43    0.907007
Apoio_Amigos               -0.089005   6.605802e-37    0.914841
Qtd_Comodos                -0.046656   1.198319e-06    0.954416
Grau_Limite_Doenca_Mental  -0.035562   6.690445e-08    0.965063
Apoio_Familiar             -0.030426   1.277183e-05    0.970032
Fuma                       -0.019885   3.396751e-03    0.980312
Estado_Civil               -0.016962   1.808188e-02    0.983181
Grau_Limite_Depressao      -0.016251   2.049799e-02    0.983881
Horas_TV                   -0.005791   3.842820e-01    0.994226
Grau_Limite_DORT            0.000145   9.843242e-01    1.000145
Acesso_Internet             0.102666   1.445071e-42    1.108121
Nivel_Instrucao             0.128839   8.994050e-67    1.137507
Cor_Raca                    0.129936   1.354251e-80    1.138756
Freq_Anedonia               0.139679   5.992254e-56    1.149905
Possui_Automovel            0.141413   6.780938e-75    1.151900
Total_Moradores             0.156515  2.057304e-102    1.169428
Freq_Problemas_Sono         0.160898   7.058223e-92    1.174566
Pratica_Exercicio           0.209254  3.870361e-195    1.232758
Possui_Computador           0.221871  1.358691e-173    1.248410
Freq_Depressao              0.233910  8.923112e-168    1.263530
Freq_Cansaco                0.265395  1.974626e-202    1.303946
Idade                       0.369466   0.000000e+00    1.446962

Regra de interpretação

Coeficiente > 0 → aumenta a chance de a pessoa ir para categorias PIORES de saúde

Coeficiente < 0 → aumenta a chance de ir para categorias MELHORES de saúde