In [1]:
import pandas as pd
from lib.utils import load_variables

In [2]:
dic = pd.read_excel("./data/dicionario_PNS_microdados_2019.xls", skiprows=1)

In [3]:
dic.head(5)

,Posição inicial,Tamanho,Código\nda\nvariável,Quesito,Unnamed: 4,Categorias,Unnamed: 6
0,NaN,NaN,NaN,nº,descrição,Tipo,Descrição
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Parte 1 - Identificação e Controle,NaN,NaN,NaN,NaN,NaN,NaN
3,1,2.0,V0001,NaN,Unidade da Federação,11,Rondônia
4,NaN,NaN,NaN,NaN,NaN,12,Acre

In [4]:
print(dic.columns.tolist())

['Posição inicial ', 'Tamanho', 'Código\nda\nvariável', 'Quesito', 'Unnamed: 4', 'Categorias', 'Unnamed: 6']

In [5]:
new_columns = { "Posição inicial ": "Posição_Inicial" ,"Código\nda\nvariável":"Código_da_Váriavel", "Unnamed: 4" : "Quesito_Descrição", "Quesito": "Quesito_N°", "Categorias": "Categorias_Tipo", "Unnamed: 6" : "Categorias_Descrição"}
dic = dic.rename(columns=new_columns)
dic = dic.dropna(subset=["Código_da_Váriavel"])
dic

,Posição_Inicial,Tamanho,Código_da_Váriavel,Quesito_N°,Quesito_Descrição,Categorias_Tipo,Categorias_Descrição
3,1,2.0,V0001,NaN,Unidade da Federação,11,Rondônia
30,3,7.0,V0024,NaN,Estrato,NaN,NaN
31,10,9.0,UPA_PNS,NaN,UPA,NaN,NaN
32,19,4.0,V0006_PNS,NaN,Número de ordem do domicílio na PNS,NaN,NaN
33,23,2.0,V0015,NaN,Tipo da entrevista,1,Realizada
...,...,...,...,...,...,...,...
5199,1536,2.0,VDL001,NaN,Idade em meses das crianças nascidas no períod...,01 a 31,Idade (em meses)
5202,1538,1.0,VDM001,NaN,Faixa de tempo gasto por dia no deslocamento c...,1,Menos de 30 minutos
5207,1539,1.0,VDP001,NaN,Tipo de cigarro industrializado comprado,1,Legal
5211,1540,1.0,VDR001,NaN,Método contraceptivo mais eficaz que faz uso,1,Ligadura das trompas (laqueadura ou esteriliza...
5221,1541,8.0,VDDATA,NaN,Data de geração do arquivo de microdados. Data...,NaN,NaN

In [6]:
col_names = dic.iloc[:,2].dropna(axis=0)
col_names

3           V0001
30          V0024
31        UPA_PNS
32      V0006_PNS
33          V0015
          ...
5199       VDL001
5202       VDM001
5207       VDP001
5211       VDR001
5221       VDDATA
Name: Código_da_Váriavel, Length: 1089, dtype: object

In [7]:
w = dic.Tamanho.dropna(axis=0).values
ww = w.astype(int)
dic.iloc[: ,2].dropna(axis=0).shape

(1089,)

In [64]:
df = pd.read_fwf("./data/PNS_2019.txt", header=None, dtype=str, widths=ww)

In [66]:
df.head(5)

,0,1,2,3,4,5,6,7,8,9,...,1078,1079,1080,1081,1082,1083,1084,1085,1086,1087
0,11,1110011,110000016,0001,01,2019,06,1,1,1,...,1,06,00002098,00000350,2,NaN,NaN,NaN,NaN,20220504
1,11,1110011,110000016,0001,01,2019,06,1,1,0,...,NaN,NaN,00002098,00000350,2,NaN,NaN,NaN,NaN,20220504
2,11,1110011,110000016,0001,01,2019,06,1,1,0,...,1,04,00002098,00000350,2,NaN,NaN,NaN,NaN,20220504
3,11,1110011,110000016,0001,01,2019,06,1,1,9,...,NaN,NaN,00002098,00000350,2,NaN,NaN,NaN,NaN,20220504
4,11,1110011,110000016,0001,01,2019,06,1,1,9,...,NaN,NaN,00002098,00000350,2,NaN,NaN,NaN,NaN,20220504

In [11]:
df.shape

(293726, 1088)

In [12]:
my_variables = load_variables("./data/my_variables_v2.pkl")

my_variables_list = ["V0001"]

for k,v in my_variables.items():
  
  for each in v:
    my_variables_list.append(each)
  
len(my_variables_list)

92

In [13]:
dic.head(5)

,Posição_Inicial,Tamanho,Código_da_Váriavel,Quesito_N°,Quesito_Descrição,Categorias_Tipo,Categorias_Descrição
3,1,2.0,V0001,NaN,Unidade da Federação,11,Rondônia
30,3,7.0,V0024,NaN,Estrato,NaN,NaN
31,10,9.0,UPA_PNS,NaN,UPA,NaN,NaN
32,19,4.0,V0006_PNS,NaN,Número de ordem do domicílio na PNS,NaN,NaN
33,23,2.0,V0015,NaN,Tipo da entrevista,1,Realizada

In [14]:
col_desc_index = {}
col_descricao_index = {}

for i, col in enumerate(col_names):
    linha = dic[dic["Código_da_Váriavel"] == col]
    
    if not linha.empty:
        descricao = linha["Quesito_Descrição"].values[0]
        col_desc_index[col] = [i, descricao]
    else:
        col_desc_index[col] = [i, None]

col_desc_index

{'V0001': [0, 'Unidade da Federação'],
 'V0024': [1, 'Estrato'],
 'UPA_PNS': [2, 'UPA'],
 'V0006_PNS': [3, 'Número de ordem do domicílio na PNS'],
 'V0015': [4, 'Tipo da entrevista'],
 'V0020': [5, 'Ano de referência'],
 'V0022': [6, 'Total de moradores'],
 'V0026': [7, 'Tipo de situação censitária'],
 'V0031': [8, 'Tipo de área'],
 'V0025A': [9,
  'Seleção do morador de 15 anos ou mais para responder o questionário individual'],
 'V0025B': [10,
  'Seleção do morador de 15 anos ou mais para ter medida antropométrica aferida'],
 'A001': [11, 'Tipo do domicílio'],
 'A002010': [12,
  'Qual é o material que predomina na construção das paredes externas deste domicílio?'],
 'A003010': [13, 'Material predominante na cobertura (telhado) do domicílio'],
 'A004010': [14, 'Qual é o material que predomina no piso deste domicílio'],
 'A01001': [15, ' Quantos cômodos têm este domicílio'],
 'A011': [16,
  'Quantos cômodos estão servindo permanentemente de dormitório para os moradores deste domicílio'],
 'A005010': [17,
  'Qual é a principal forma de abastecimento de água deste domicílio'],
 'A005012': [18,
  'Este domicílio está ligado à rede geral de distribuição de água? '],
 'A00601': [19, ' A água utilizada neste domicílio chega'],
 'A009010': [20, ' A água utilizada para beber neste domicílio é'],
 'A01401': [21,
  'Quantos banheiros (com chuveiro ou banheira e vaso sanitário ou privada) de uso exclusivo dos moradores existem neste domicílio, inclusive os localizados no terreno ou propriedade'],
 'A01402': [22,
  'Quantos banheiros (com chuveiro ou banheira e vaso sanitário ou privada) de uso comum a mais de um domicilio, existem neste terreno ou propriedade'],
 'A01403': [23,
  'Utiliza sanitário ou buraco para dejeções, inclusive os localizados no terreno ou na propriedade (cercado por paredes de qualquer material'],
 'A01501': [24,
  'Para onde vai o esgoto do banheiro? Ou Para onde vai o esgoto do sanitário ou do buraco para dejeções?'],
 'A016010': [25, 'Qual o (principal) destino dado ao lixo'],
 'A018011': [26, 'Neste domicílio existe televisão em cores '],
 'A018012': [27, 'Quantos?'],
 'A018013': [28, 'Neste domicílio existe geladeira '],
 'A018014': [29, 'Quantos?'],
 'A018015': [30, 'Neste domicílio existe máquina de lavar roupa '],
 'A018016': [31, 'Quantos?'],
 'A018017': [32, 'Neste domicílio existe telefone fixo convencional'],
 'A018018': [33, 'Quantos?'],
 'A018019': [34, 'Neste domicílio existe telefone móvel celular '],
 'A018020': [35, 'Quantos?'],
 'A018021': [36, 'Neste domicílio existe forno micro-ondas'],
 'A018022': [37, 'Quantos?'],
 'A018023': [38,
  'Neste domicílio existe computador (considere inclusive os portáteis, tais como: laptop, notebook ou netbook)?  '],
 'A018024': [39, 'Quantos?'],
 'A018025': [40, 'Neste domicílio existe motocicleta'],
 'A018026': [41, 'Quantos?'],
 'A018027': [42, 'Neste domicílio existe automóvel'],
 'A018028': [43, 'Quantos?'],
 'A01901': [44,
  'Algum morador tem acesso à Internet no domicílio por meio de computador, tablet, telefone móvel celular, televisão ou outro equipamento?'],
 'A02101': [45,
  'No seu domicílio, há trabalhador (as) doméstico(as) que trabalham em seu domicílio três vezes ou mais por semana (empregada doméstica, babá, cuidador etc.)'],
 'A02102': [46, 'Quantos?'],
 'A02201': [47, ' Em seu domicílio, há algum animal de estimação'],
 'A02305': [48, 'Quantos destes animais são gatos'],
 'A02306': [49, 'Quantos destes animais são cachorros'],
 'A02307': [50, 'Quantos destes animais são aves'],
 'A02308': [51, 'Quantos destes animais são peixes'],
 'A02401': [52,
  'Nos últimos 12 meses, quantos gatos foram vacinados contra raiva?'],
 'A02402': [53,
  'Nos últimos 12 meses , quantos cachorros foram vacinados contra raiva?'],
 'B001': [54,
  'O seu domicílio está cadastrado na unidade de saúde da família '],
 'B002': [55, '. Quando o seu domicílio foi cadastrado'],
 'B003': [56,
  'Nos últimos doze meses, com que frequência o seu domicílio recebeu uma visita de algum Agente Comunitário ou algum membro da Equipe de Saúde da Família? '],
 'B004': [57,
  'Nos últimos doze meses, com que frequência o seu domicílio recebeu uma visita de algum agente de endemias (como a dengue, por exemplo)'],
 'C001': [58, 'Número de pessoas no domicílio'],
 'C00301': [59, 'Número de ordem do morador'],
 'C004': [60, 'Condição no domicílio'],
 'C006': [61, 'Sexo'],
 'C00701': [62, 'Dia de nascimento'],
 'C00702': [63, 'Mês de nascimento'],
 'C00703': [64, 'Ano de nascimento'],
 'C008': [65, 'Idade do morador na data de referência'],
 'C009': [66, 'Cor ou raça'],
 'C01001': [67, 'Cônjuge ou companheiro(a) mora em nesse domicílio.'],
 'C010010': [68, 'Número de ordem do cônjuge ou companheiro(a)'],
 'C013': [69, 'Cônjuge ou companheiro(a) mora em outro domicílio.'],
 'C014': [70, 'Qual é a natureza dessa união? '],
 'C015': [71, 'Esta união é registrada em cartório? '],
 'C016': [72, 'Foi realizada cerimônia religiosa para esta união? '],
 'C017': [73, '___já viveu com cônjuge ou companheiro (a) antes? '],
 'C018': [74,
  'Que idade ___tinha quando começou a viver com seu(sua) primeiro(a)/único(a) marido (mulher) ou companheiro(a)?  '],
 'C01801': [75,
  'Que idade ___tinha quando começou a viver com seu(sua) primeiro(a)/único(a) marido (mulher) ou companheiro(a)?   '],
 'C011': [76, 'Qual é o estado civil de ___? '],
 'C012': [77, 'Informante do Módulo C'],
 'D001': [78, 'Sabe ler e escrever'],
 'D00201': [79, 'Frequenta escola ou creche'],
 'D00202': [80, 'A escola que frequenta é da'],
 'D00301': [81, 'Qual é o curso que frequenta'],
 'D00501': [82, ' Esse curso que ___ frequenta é dividido em'],
 'D006': [83, 'Qual é o ano/semestre/série que ___frequenta?'],
 'D00601 ': [84, 'Qual é a etapa do ensino fundamental que ___ frequenta'],
 'D007': [85, ' ___já concluiu algum outro curso superior de graduação'],
 'D008': [86, 'Anteriormente ___frequentou escola ou creche'],
 'D00901': [87, 'Qual foi o curso mais elevado que ___frequentou '],
 'D010': [88, 'A duração deste curso que ___frequentou anteriormente era de'],
 'D01101': [89, 'Este curso que ___ frequentou anteriormente era dividido em'],
 'D01201': [90,
  'concluiu, com aprovação, pelo menos o primeiro ano/semestre/série deste curso que frequentou '],
 'D01301': [91,
  'Qual foi o último ano/semestre/série que ___ concluiu, com aprovação, neste curso que frequentou '],
 'D01302': [92, 'Qual foi a etapa de ensino fundamental que ___frequentou'],
 'D01303': [93, '___concluiu os anos iniciais deste curso que frequentou '],
 'D014': [94, '___concluiu este curso que frequentou '],
 'D015': [95, 'Informante do Módulo D'],
 'E001': [96,
  'Na semana de___ a___ (semana de referência), ___ trabalhou ou estagiou, durante pelo menos uma hora, em alguma atividade remunerada em dinheiro'],
 'E002': [97,
  'Na semana de ___a___ (semana de referência), ___ trabalhou ou estagiou, durante pelo menos uma hora, em alguma atividade remunerada em produtos, mercadorias, moradia, alimentação, treinamento ou aprendizado etc'],
 'E003': [98,
  'Na semana de ___ a ___ (semana de referência), ___ fez algum bico ou trabalhou em alguma atividade ocasional remunerada durante pelo menos 1 hora'],
 'E004': [99,
  'Na semana de ___ a ___ (semana de referência), ___ ajudou durante pelo menos 1 hora, sem receber pagamento, no trabalho remunerado de algum morador do domicílio ou de parente'],
 'E005': [100,
  'Na semana de ___ a ___ (semana de referência), ___ tinha algum trabalho remunerado do qual estava temporariamente afastado'],
 'E006011': [101,
  'Na semana de ___ a ___ (semana de referência), por que motivo ___ estava afastado desse trabalho'],
 'E008': [102, 'A doença ou acidente foi relacionado ao trabalho?'],
 'E010010': [103,
  ' Em ___ /___ /___ (último dia da semana de referência), fazia quanto tempo que ___ estava afastado desse trabalho'],
 'E010011': [104, 'Tempo que estava afastado (De 1 mês a menos de 1 ano)'],
 'E010012': [105, 'Tempo que estava afastado (De 1 ano a menos de 2 anos) '],
 'E010013': [106, 'Tempo que estava afastado (De 2 anos a 98 anos)'],
 'E011': [107, 'Quantos trabalhos ___tinha na semana de ___ a ___ '],
 'E01201': [108,
  'Qual era a ocupação (cargo ou função) que ___ tinha nesse trabalho'],
 'E01401': [109, 'Nesse trabalho, ___ era'],
 'E014011': [110,
  'Trabalhador não remunerado em ajuda a membro do domicílio ou parente '],
 'E01402': [111,
  'Nesse trabalho, ___era servidor público estatutário (federal, estadual ou municipal)'],
 'E01403': [112, 'Nesse trabalho, ___tinha carteira de trabalho assinada'],
 'E01501': [113, 'Qual era a principal atividade desse negócio/empresa'],
 'E01601': [114,
  '...recebia/fazia normalmente nesse trabalho rendimento/retirada em dinheiro?'],
 'E01602': [115,
  'Qual era o rendimento bruto mensal ou retirada que ___ fazia normalmente nesse trabalho?(valor em dinheiro)'],
 'E01603': [116,
  '...recebia/fazia normalmente nesse trabalho rendimento/retirada em produtos ou mercadorias?'],
 'E01604': [117,
  'Qual era o rendimento bruto mensal ou retirada que ___ fazia normalmente nesse trabalho?(valor estimado em produtos ou mercadorias)'],
 'E01605': [118,
  '...recebia/fazia normalmente nesse trabalho rendimento/retirada somente em benefícios ?'],
 'E017': [119,
  'Quantas horas ___ trabalhava normalmente, por semana, nesse trabalho?'],
 'E01801': [120,
  '...recebia/fazia normalmente nesse(s) outro(s) trabalho(s) rendimento/retirada em dinheiro?'],
 'E01802': [121,
  'Qual era o rendimento bruto mensal ou retirada que ___ fazia normalmente nesse(s) outro(s) trabalho(s)?(valor em dinheiro)'],
 'E01803': [122,
  '...recebia/fazia normalmente nesse(s) outro(s) trabalho(s) rendimento/retirada em produtos ou mercadorias?'],
 'E01804': [123,
  'Qual era o rendimento bruto mensal ou retirada que ___ fazia normalmente nesse(s) outro(s) trabalho(s)?(valor estimado em produtos ou mercadorias)'],
 'E01805': [124,
  '...recebia/fazia normalmente nesse(s) outro(s) trabalho(s) rendimento/retirada somente em benefícios ?'],
 'E019': [125,
  'Quantas horas ___ trabalhava normalmente, por semana, nesses outros trabalhos? '],
 'E022': [126,
  'No período de ___ a ___ (período de referência de 30 dias), ___ tomou alguma providência para conseguir trabalho, seja um emprego ou um negócio próprio? '],
 'E023011': [127,
  'No período de ___ a ___ (período de referência de 30 dias), qual foi a principal providência que ___ tomou para conseguir trabalho? '],
 'E024011': [128,
  'Qual foi o principal motivo de ___ não ter tomado providência para conseguir trabalho no período de ___ a ___ (período de referência de 30 dias)?'],
 'E02402': [129,
  'Quanto tempo depois de __/__/__ (último dia da semana de referência) ___ irá começar esse trabalho que conseguiu?'],
 'E024021': [130, 'Número de meses para começar o trabalho que conseguiu.'],
 'E025': [131,
  'Até o dia ___ (último dia da semana de referência), fazia quanto tempo que___ estava sem qualquer trabalho e tentando conseguir trabalho?'],
 'E02501': [132,
  'fazia quanto tempo que vinha procurando trabalho (de 1 mês a menos de 1 ano)'],
 'E02502': [133,
  'fazia quanto tempo que vinha procurando trabalho (de 1 ano a menos de 2 anos)'],
 'E02503': [134,
  'fazia quanto tempo vinha procurando trabalho (2 anos ou mais)'],
 'E026': [135,
  'Se tivesse conseguido um trabalho ___ poderia ter começado a trabalhar na semana de___ a ___ (semana de referência)'],
 'E02601': [136,
  'No período de ___ a ___ (período de referência de 358 dias), ___ trabalhou, por pelo menos 1 hora?'],
 'E02801': [137,
  'Na semana de ___a___ (semana de referência), ___ realizou tarefas de cuidados de moradores deste domicílio que eram crianças, idosos, enfermos ou pessoas com necessidades especiais, tais como: Auxiliar nos cuidados pessoais (alimentar, vestir, pentear, dar remédio, dar banho, colocar para dormir)'],
 'E02802': [138,
  'Na semana de ___a___ (semana de referência), ___ realizou tarefas de cuidados de moradores deste domicílio que eram crianças, idosos, enfermos ou pessoas com necessidades especiais, tais como: Auxiliar em atividades educacionais'],
 'E02803': [139,
  'Na semana de ___a___ (semana de referência), ___ realizou tarefas de cuidados de moradores deste domicílio que eram crianças, idosos, enfermos ou pessoas com necessidades especiais, tais como: Ler, jogar ou brincar'],
 'E02804': [140,
  'Na semana de ___a___ (semana de referência), ___ realizou tarefas de cuidados de moradores deste domicílio que eram crianças, idosos, enfermos ou pessoas com necessidades especiais, tais como: Monitorar ou fazer companhia dentro do domicílio'],
 'E02805': [141,
  'Na semana de ___a___ (semana de referência), ___ realizou tarefas de cuidados de moradores deste domicílio que eram crianças, idosos, enfermos ou pessoas com necessidades especiais, tais como: Transportar ou acompanhar para escola, médico, exames, parque, praça, atividades sociais, culturais, esportivas ou religiosas'],
 'E02806': [142, 'Outras tarefas de cuidados de moradores do domicílio'],
 'E030': [143,
  'Na semana de ___ a ___ (semana de referência), ___ cuidou de parentes que não moravam neste domicílio e que precisavam de cuidados (crianças, idosos, enfermos ou pessoas com necessidades especiais)? '],
 'E03101': [144,
  'Na semana de___a___ (semana de referência), ___fez tarefas domésticas para o próprio domicílio, tais como: preparar ou servir alimentos, arrumar a mesa ou lavar as louças?'],
 'E03102': [145,
  'Na semana de___a___ (semana de referência), ___fez tarefas domésticas para o próprio domicílio, tais como: cuidar da limpeza ou manutenção de roupas e sapatos/'],
 'E03103': [146,
  'Na semana de___a___ (semana de referência), ___fez tarefas domésticas para o próprio domicílio, tais como: fazer pequenos reparos ou manutenção do domicílio, do automóvel, de eletrodomésticos ou outros equipamentos? '],
 'E03104': [147,
  'Na semana de___a___ (semana de referência), ___fez tarefas domésticas para o próprio domicílio, tais como: Limpar ou arrumar o domicílio, a garagem, o quintal ou o jardim? '],
 'E03105': [148,
  'Na semana de___a___ (semana de referência), ___fez tarefas domésticas para o próprio domicílio, tais como: Cuidar da organização do domicílio (pagar contas, contratar serviços, orientar empregados etc.)? '],
 'E03106': [149,
  'Na semana de___a___ (semana de referência), ___fez tarefas domésticas para o próprio domicílio, tais como: Fazer compras ou pesquisar preços de bens para o domicílio? '],
 'E03107': [150,
  'Na semana de___a___ (semana de referência), ___fez tarefas domésticas para o próprio domicílio, tais como: Cuidar dos animais domésticos? '],
 'E03108': [151,
  'Na semana de___a___ (semana de referência), ___fez tarefas domésticas para o próprio domicílio, tais como: Outras tarefas domésticas?'],
 'E032': [152,
  '. Na semana de___a___ (semana de referência), ___fez alguma tarefa doméstica em domicílio de parente? '],
 'E033': [153,
  '. Na semana de___a___ (semana de referência), ___ qual foi o total de horas que dedicou às atividades de cuidados de pessoas e/ou afazeres domésticos? '],
 'E027': [154, 'Informante do Módulo E'],
 'F001011': [155,
  'Em (mês da pesquisa) ___ recebia normalmente rendimento de aposentadoria ou pensão de instituto de previdência federal (INSS), estadual, municipal, ou do governo federal, estadual, municipal?'],
 'F001021': [156, 'Valor habitualmente recebido'],
 'F007011': [157,
  'Em (mês da pesquisa), ___ recebia normalmente rendimento de pensão alimentícia, doação ou mesada em dinheiro de pessoa que não morava no domicílio?'],
 'F007021': [158, 'Valor habitualmente recebido'],
 'F008011': [159,
  'Em (mês da pesquisa), ___ recebia normalmente rendimento de aluguel ou arrendamento?'],
 'F008021': [160, 'Valor habitualmente recebido'],
 'VDF001': [161,
  'Em (mês da pesquisa), _______ recebia normalmente algum juro de caderneta de poupança e de outras aplicações financeiras, dividendos, programas sociais, seguro-desemprego, seguro defeso ou outros rendimentos? '],
 'VDF00102': [162, 'Valor recebido em reais (VDF001)'],
 'F016': [163, 'Informante do Módulo F'],
 'G033': [164,
  '. ___ usa óculos ou outro aparelho de auxílio para lidar com problemas de visão? '],
 'G034': [165, '____________ faz uso de óculos? '],
 'G035': [166, 'Os óculos foram obtidos no SUS? '],
 'G036': [167, '____________ faz uso de lentes de contato? '],
 'G038': [168, '____________ faz uso de lupas ou lentes especiais? '],
 'G039': [169, 'As lupas ou lentes especiais foram obtidos no SUS? '],
 'G040': [170, '____________ faz uso de bengala articulada? '],
 'G041': [171, 'A bengala articulada foi obtida no SUS? '],
 'G042': [172, '____________ faz uso de cão guia? '],
 'G044': [173,
  ' ____________ faz uso de algum outro aparelho de auxílio para lidar com problemas de visão? '],
 'G046': [174,
  '. ___ tem dificuldade permanente de enxergar mesmo usando óculos, lentes de contato ou lupas? '],
 'G047': [175, ' ___ tem dificuldade permanente de enxergar? '],
 'G048': [176,
  '___ usa aparelho auditivo ou outro aparelho de auxílio para ouvir melhor? '],
 'G049': [177, '____________ faz uso de aparelho auditivo '],
 'G050': [178, 'O aparelho auditivo foi obtido no SUS? '],
 'G051': [179, '____________ faz uso de implante coclear? '],
 'G052': [180, 'O implante coclear foi obtido no SUS? '],
 'G053': [181,
  '____________ faz uso de sistema de frequência modulada individual (sistema FM)? '],
 'G054': [182,
  'O sistema de frequência modulada individual (sistema FM) foi obtido no SUS? '],
 'G055': [183,
  '____________ faz uso de algum outro aparelho de auxílio para ouvir melhor? '],
 'G057': [184,
  ' ___ tem dificuldade permanente de ouvir mesmo usando aparelhos auditivos? (Para moradores com 5 anos ou mais de idade.) \n\nOU\n ___ tem dificuldade permanente para ouvir sons como vozes ou música, mesmo usando aparelhos auditivos? (Para moradores com 2 a 4 anos de idade.)\n\n'],
 'G058': [185,
  '___ tem dificuldade permanente de ouvir? (Para moradores com 5 anos ou mais de idade.)\n\nOU\n\n___ tem dificuldade permanente de ouvir sons como vozes ou música? (Para moradores com 2 a 4 anos de idade.)\n'],
 'G05801': [186,
  'Sabe usar a Língua Brasileira de Sinais – Libras? (Para moradores com 5 anos ou mais de idade.)'],
 'G059': [187, '___ usa algum aparelho de auxílio para se locomover? '],
 'G060': [188, '____________ faz uso de cadeira de rodas? '],
 'G061': [189, 'A cadeira de rodas foi obtida no SUS? '],
 'G062': [190, '____________ faz uso de bengala, muletas ou andador? '],
 'G063': [191, 'A bengala, muletas ou andador foram obtidas no SUS? '],
 'G064': [192, '____________ faz uso de prótese? '],
 'G065': [193, 'A prótese foi obtida no SUS? '],
 'G066': [194, '____________ faz uso de órtese? '],
 'G067': [195, 'A órtese foi obtida no SUS? '],
 'G068': [196,
  '____________ faz uso de algum outro aparelho de auxílio para se locomover? '],
 'G070': [197,
  '___ tem dificuldade permanente de caminhar ou subir degraus, mesmo usando prótese, bengala ou outro aparelho de auxílio? (Para moradores com 5 anos ou mais de idade.)\n\nOU\n\nComparado com crianças da mesma idade, ___ tem dificuldade permanente para caminhar, mesmo usando prótese, bengala ou aparelho de auxílio? (Para moradores com 2 a 4 anos de idade.)\n'],
 'G071': [198,
  '___ tem dificuldade permanente de caminhar ou subir degraus? (Para moradores com 5 anos ou mais de idade.)\n\nOU\n\nComparado com crianças da mesma idade, ___ tem dificuldade permanente para caminhar? (Para moradores com 2 a 4 anos de idade.)\n'],
 'G072': [199,
  '___ usa algum aparelho de auxílio para realizar movimentos com os membros superiores? '],
 'G073': [200, '____________ faz uso de prótese para os membros superiores? '],
 'G074': [201, 'A prótese para os membros superiores foi obtida no SUS? '],
 'G075': [202, '____________ faz uso de órtese para os membros superiores? '],

In [15]:
indices_para_manter = [col_desc_index.get(col)[0] for col in my_variables_list if col in col_desc_index]
descricoes_para_manter = [col_desc_index.get(col)[1] for col in my_variables_list if col in col_desc_index]

indices_para_dropar = [i for i in range(len(df.columns)) if i not in indices_para_manter]

df_filter = df.drop(df.columns[indices_para_dropar], axis=1)
df_filter.shape

(293726, 92)

In [16]:
len(descricoes_para_manter)

92

In [17]:
df_filter.head(20)

,0,61,65,66,76,78,79,87,94,155,...,586,587,589,593,597,620,621,622,632,633
0,11,2,055,1,1,1,2,05,1,2,...,1,NaN,1,2,1,1,1,2,NaN,NaN
1,11,1,069,4,1,1,2,NaN,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11,1,031,2,4,1,2,10,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,11,1,009,2,NaN,1,1,NaN,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11,2,006,4,NaN,1,1,NaN,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,11,2,004,2,NaN,NaN,1,NaN,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,11,2,033,1,4,1,2,07,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,11,1,017,1,4,1,1,NaN,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,11,2,015,4,4,1,1,NaN,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,11,2,019,4,4,1,2,10,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,2,2,NaN,NaN
10,11,2,045,2,4,1,2,10,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,1,2,NaN,NaN
11,11,2,078,4,4,1,2,06,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,11,1,028,2,4,1,2,10,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,11,2,025,4,4,1,2,10,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,11,2,026,4,4,1,2,10,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,11,2,007,4,NaN,1,1,NaN,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,11,2,003,4,NaN,NaN,1,NaN,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,11,2,003,4,NaN,NaN,1,NaN,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,11,2,058,2,3,2,2,04,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,2,2,NaN,NaN
19,11,2,028,4,4,1,1,NaN,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,2,2,NaN,NaN

In [18]:
indices_para_manter = list(dict.fromkeys(indices_para_manter))
descricoes_para_manter = [col_desc_index[col][1] for col in my_variables_list 
                          if col in col_desc_index]
indices_unicos = set(indices_para_manter)
descricoes_para_manter = [col_desc_index[col][1] for col in my_variables_list 
                          if col in col_desc_index and col_desc_index[col][0] in indices_unicos]

In [19]:
df_filter = df[df.columns[indices_para_manter]]
df_filter

,0,61,65,66,76,78,79,87,94,155,...,586,587,593,597,589,622,633,632,620,621
0,11,2,055,1,1,1,2,05,1,2,...,1,NaN,2,1,1,2,NaN,NaN,1,1
1,11,1,069,4,1,1,2,NaN,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11,1,031,2,4,1,2,10,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,11,1,009,2,NaN,1,1,NaN,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11,2,006,4,NaN,1,1,NaN,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
293721,53,2,049,2,4,1,2,10,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293722,53,1,084,4,3,1,2,14,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293723,53,1,021,1,4,1,1,NaN,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293724,53,2,013,4,4,1,1,NaN,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293725,53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
from collections import Counter

contador = Counter(indices_para_manter)
duplicados = [idx for idx, count in contador.items() if count > 1]

print("Duplicados:", duplicados)


indices_para_manter = list(dict.fromkeys(indices_para_manter))


descricoes_para_manter = []
seen_indices = set()
for col in my_variables_list:
    if col in col_desc_index:
        idx, desc = col_desc_index[col]
        if idx not in seen_indices:
            descricoes_para_manter.append(desc)
            seen_indices.add(idx)

df_filter = df[df.columns[indices_para_manter]]
df_filter.columns = descricoes_para_manter

print(len(df_filter.columns), len(descricoes_para_manter))

Duplicados: []
92 92

In [21]:
df_filter.columns = descricoes_para_manter
df_filter.columns

Index(['Unidade da Federação', 'Sexo',
       'Idade do morador na data de referência', 'Cor ou raça',
       'Qual é o estado civil de ___? ', 'Sabe ler e escrever',
       'Frequenta escola ou creche',
       'Qual foi o curso mais elevado que ___frequentou ',
       '___concluiu este curso que frequentou ',
       'Em (mês da pesquisa) ___ recebia normalmente rendimento de aposentadoria ou pensão de instituto de previdência federal (INSS), estadual, municipal, ou do governo federal, estadual, municipal?',
       'Em (mês da pesquisa), ___ recebia normalmente rendimento de pensão alimentícia, doação ou mesada em dinheiro de pessoa que não morava no domicílio?',
       'Em (mês da pesquisa), ___ recebia normalmente rendimento de aluguel ou arrendamento?',
       'tem algum plano odontológico particular, de empresa ou órgão público?',
       'tem algum plano de saúde médico particular, de empresa ou órgão público?',
       'Quantos?',
       'Quem é o titular do plano de saúde médico (único ou principal)?',
       'Há quanto tempo sem interrupção _____ possui esse plano de saúde (único ou principal)? ',
       ' ___ considera este plano de saúde: ',
       'O plano de saúde médico (único ou principal) que _____ possui é de instituição de assistência de servidor público (municipal, estadual ou militar)? ',
       'O plano de saúde (único ou principal) de assistência médica que ___ possui dá direito a consultas',
       'O plano de saúde (único ou principal) de assistência médica que ___ possui dá direito a exames',
       'O plano de saúde (único ou principal) de assistência médica que ___ possui dá direito a internações',
       'O plano de saúde (único ou principal) de assistência médica que ___ possui dá direito a partos',
       'Quem paga a mensalidade deste plano de saúde?',
       ' Nas duas últimas semanas, ___ deixou de realizar quaisquer de suas atividades habituais (trabalhar, ir à escola, brincar, afazeres domésticos etc.) por motivo da própria saúde',
       'Nas duas últimas semanas, quantos dias _____ deixou de realizar suas atividades habituais, por motivo da própria saúde',
       ' Qual foi o principal motivo de saúde que impediu ___ de realizar suas atividades habituais nas duas últimas semanas ',
       'Este motivo de saúde estava relacionado ao trabalho',
       'Nas duas últimas semanas___ esteve acamado (a)',
       'Nas duas últimas semanas, quantos dias _____ esteve acamado (a)',
       'Algum médico já deu o diagnóstico de alguma doença crônica, física ou mental, ou doença de longa duração (de mais de 6 meses de duração) a ___',
       'Alguma dessas doenças limita de alguma forma suas atividades habituais (trabalhar, ir à escola, brincar, afazeres domésticos, etc.)',
       ' ___ costuma procurar o mesmo lugar, mesmo médico ou mesmo serviço de saúde quando precisa de atendimento de saúde',
       'Quando está doente ou precisando de atendimento de saúde___ costuma procurar',
       'Quando ____ consultou um médico pela última vez',
       'Quando ___ consultou um dentista pela última vez',
       'Nas duas últimas semanas, ___ procurou algum lugar, serviço ou profissional de saúde para atendimento relacionado à própria saúde',
       'Qual foi o motivo principal pelo qual ___ procurou atendimento relacionado à própria saúde nas duas últimas semanas',
       'Onde ___ procurou o primeiro atendimento de saúde por este motivo nas duas últimas semanas',
       'Nessa primeira vez que procurou atendimento de saúde por este motivo, nas duas últimas semanas',
       'Por que motivo ___ não foi atendido(a) na primeira vez que procurou atendimento de saúde nas duas últimas semanas',
       'Nas duas últimas semanas, quantas vezes ___ voltou a procurar atendimento de saúde por este mesmo motivo',
       'Onde ___ procurou o último atendimento de saúde por este motivo nas duas últimas semanas',
       'Em geral, como o(a) Sr(a) avalia a sua saúde',
       'Peso - Informado (em kg)\n(3 inteiros e 1 casa decimal)',
       'Altura - Informada (em cm)\n(3 inteiros)',
       'Em quantos dias da semana o(a) Sr(a) costuma comer feijão? ',
       'Em quantos dias da semana, o(a) Sr(a) costuma comer pelo menos um tipo de verdura ou legume (sem contar batata, mandioca, cará ou inhame) como alface, tomate, couve, cenoura, chuchu, berinjela, abobrinha? ',
       'Em geral, o(a) Sr(a) costuma comer esse tipo de verdura ou legume: ',
       'Em quantos dias da semana o(a) Sr(a) costuma comer carne vermelha (boi, porco, cabrito, bode, ovelha etc.)? ',
       'Em quantos dias da semana o(a) Sr(a) costuma comer frango/galinha? ',
       'Em quantos dias da semana o(a) Sr(a) costuma comer peixe? ',
       'Em quantos dias da semana o(a) Sr(a) costuma tomar refrigerante? ',
       'Que tipo de refrigerante o(a) Sr(a) costuma tomar? ',
       'Em quantos dias da semana o(a) Sr(a) costuma tomar suco de caixinha/lata ou refresco em pó ? ',
       'Em quantos dias da semana o(a) Sr(a) costuma tomar suco de fruta natural (incluída a polpa de fruta congelada)? ',
       'Em quantos dias da semana o(a) Sr(a) costuma comer frutas? ',
       'Em geral, quantas vezes por dia o(a) Sr(a) come frutas? ',
       'Em quantos dias da semana o(a) Sr(a) costuma tomar leite? (de origem animal: vaca, cabra, búfala etc.) ',
       'Que tipo de leite o(a) Sr(a) costuma tomar? ',
       'Em quantos dias da semana o(a) Sr(a) costuma comer alimentos doces como biscoito/bolacha recheado, chocolate, gelatina, balas e outros?',
       'Em quantos dias da semana o(a) Sr(a) costuma substituir a refeição do almoço por lanches rápidos como sanduíches, salgados, pizza, cachorro quente, etc? ',
       'Considerando a comida preparada na hora e os alimentos industrializados, o(a) Sr(a) acha que o seu consumo de sal é:',
       'Nos últimos três meses, o(a) Sr(a) praticou algum tipo de exercício físico ou esporte? ',
       'Quantos dias por semana o(a) Sr(a) costuma  (costumava)praticar exercício físico ou esporte?',
       'Em geral, no dia que o(a) Sr(a) pratica exercício ou esporte, quanto tempo em horas dura essa atividade? Horas ',
       'Em geral, no dia que o(a) Sr(a) pratica (praticava) exercício ou esporte, quanto tempo em minutos dura essa atividade?Minutos ',
       'Qual o exercício físico ou esporte que o(a) Sr(a) pratica (praticava) com mais frequência? (Anotar apenas o primeiro citado) ',
       'No seu trabalho, o(a) Sr(a) anda bastante a pé? ',
       'No seu trabalho, o(a) Sr(a) faz faxina pesada, carrega peso ou faz outra atividade pesada que requer esforço físico intenso? ',
       'Em uma semana normal, em quantos dias, o(a) Sr(a) anda bastante a pé ou faz essas atividades pesadas ou que requerem esforço físico no seu trabalho?',
       'Em um dia normal, quanto tempo o(a) Sr(a) passa andando bastante a pé ou realizando essas atividades pesadas ou que requerem esforço físico no seu trabalho?Horas ',
       'Para ir ou voltar do trabalho, o(a) Sr(a) faz algum trajeto a pé ou de bicicleta? ',
       'Quantos dias por semana o(a) Sr(a) faz algum trajeto a pé ou bicicleta? ',
       'Quanto tempo o(a) Sr(a) gasta, por dia, para percorrer este trajeto a pé ou de bicicleta, considerando a ida e a volta do trabalho?Horas ',
       'Quanto tempo o(a) Sr(a) gasta, por dia, para percorrer este trajeto a pé ou de bicicleta, considerando a ida e a volta do trabalho?Minutos',
       'Com que frequência o(a) Sr(a) costuma consumir alguma bebida alcoólica?',
       'Quantos dias por semana o(a) Sr(a) costuma consumir alguma bebida alcoólica? ',
       'Em geral, no dia que o(a) Sr(a) bebe, quantas doses de bebida alcoólica o(a) Sr(a) consome? ',
       'Quando isso ocorreu, qual foi o número máximo de doses consumido em uma única ocasião?',
       'Nos últimos doze meses, quando consumiu bebida alcoólica, o(a) Sr(a) dirigiu logo depois de beber? ',
       'Algum médico já lhe deu o diagnóstico de hipertensão arterial (pressão alta)? ',
       'O(A) Sr(a) vai ao médico/serviço de saúde regularmente para acompanhamento da hipertensão arterial (pressão alta) ? ',
       'Qual o principal motivo do(a) Sr (a) não visitar o médico/serviço de saúde regularmente para acompanhamento da hipertensão arterial (pressão alta)? ',
       'O(A) Sr(a) pagou algum valor pelos medicamentos? ',
       'Esse atendimento foi feito pelo SUS? ',
       'Nas duas últimas semanas, o(a) Sr(a) tomou os medicamentos para controlar a hipertensão arterial (pressão alta)? ',
       'Algum médico já lhe deu o diagnóstico de diabetes? ',
       'Algum médico já lhe receitou insulina para controlar o Diabetes? ',
       'O(A) Sr(a) pagou algum valor pelos medicamentos orais para diabetes? ',
       'Em geral, em que grau a hipertensão ou alguma complicação da hipertensão limita as suas atividades habituais (como trabalhar, estudar, realizar afazeres domésticos etc.)? ',
       'Quando foi a última vez que o(a) Sr(a) fez exame de sangue para medir a glicemia, isto é, o açúcar no sangue? '],
      dtype='object')

In [22]:
df_filter

,Unidade da Federação,Sexo,Idade do morador na data de referência,Cor ou raça,Qual é o estado civil de ___?,Sabe ler e escrever,Frequenta escola ou creche,Qual foi o curso mais elevado que ___frequentou,___concluiu este curso que frequentou,"Em (mês da pesquisa) ___ recebia normalmente rendimento de aposentadoria ou pensão de instituto de previdência federal (INSS), estadual, municipal, ou do governo federal, estadual, municipal?",...,O(A) Sr(a) vai ao médico/serviço de saúde regularmente para acompanhamento da hipertensão arterial (pressão alta) ?,Qual o principal motivo do(a) Sr (a) não visitar o médico/serviço de saúde regularmente para acompanhamento da hipertensão arterial (pressão alta)?,O(A) Sr(a) pagou algum valor pelos medicamentos?,Esse atendimento foi feito pelo SUS?,"Nas duas últimas semanas, o(a) Sr(a) tomou os medicamentos para controlar a hipertensão arterial (pressão alta)?",Algum médico já lhe deu o diagnóstico de diabetes?,Algum médico já lhe receitou insulina para controlar o Diabetes?,O(A) Sr(a) pagou algum valor pelos medicamentos orais para diabetes?,"Em geral, em que grau a hipertensão ou alguma complicação da hipertensão limita as suas atividades habituais (como trabalhar, estudar, realizar afazeres domésticos etc.)?","Quando foi a última vez que o(a) Sr(a) fez exame de sangue para medir a glicemia, isto é, o açúcar no sangue?"
0,11,2,055,1,1,1,2,05,1,2,...,1,NaN,2,1,1,2,NaN,NaN,1,1
1,11,1,069,4,1,1,2,NaN,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11,1,031,2,4,1,2,10,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,11,1,009,2,NaN,1,1,NaN,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11,2,006,4,NaN,1,1,NaN,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
293721,53,2,049,2,4,1,2,10,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293722,53,1,084,4,3,1,2,14,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293723,53,1,021,1,4,1,1,NaN,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293724,53,2,013,4,4,1,1,NaN,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293725,53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
df_filter.to_csv("./data/df_filter.csv", index=False, encoding="utf-8")

In [ ]:
percentual_nans_colunas = df_filter.isna().mean() * 100

colunas_80pc_nans = percentual_nans_colunas[percentual_nans_colunas >= 80].index.tolist()

print("Colunas com ≥80% de NaN:", colunas_80pc_nans)
print(len(colunas_80pc_nans))

In [25]:
df_filter = df_filter.drop(columns=colunas_80pc_nans)

In [27]:
percentual_nans_linhas = df_filter.isna().mean(axis=1) * 100

linhas_80pc_nans = df.index[percentual_nans_linhas >= 80].tolist()

print("Linhas com ≥80% de NaN:", len(linhas_80pc_nans))

Linhas com ≥80% de NaN: 14344

In [29]:
df_filter = df_filter.drop(index=linhas_80pc_nans)

In [30]:
df_filter.shape

(279382, 44)

In [31]:
list(df_filter.columns)

['Unidade da Federação',
 'Sexo',
 'Idade do morador na data de referência',
 'Cor ou raça',
 'Qual é o estado civil de ___? ',
 'Sabe ler e escrever',
 'Frequenta escola ou creche',
 'Qual foi o curso mais elevado que ___frequentou ',
 '___concluiu este curso que frequentou ',
 'Em (mês da pesquisa) ___ recebia normalmente rendimento de aposentadoria ou pensão de instituto de previdência federal (INSS), estadual, municipal, ou do governo federal, estadual, municipal?',
 'Em (mês da pesquisa), ___ recebia normalmente rendimento de pensão alimentícia, doação ou mesada em dinheiro de pessoa que não morava no domicílio?',
 'Em (mês da pesquisa), ___ recebia normalmente rendimento de aluguel ou arrendamento?',
 'tem algum plano odontológico particular, de empresa ou órgão público?',
 'tem algum plano de saúde médico particular, de empresa ou órgão público?',
 ' Nas duas últimas semanas, ___ deixou de realizar quaisquer de suas atividades habituais (trabalhar, ir à escola, brincar, afazeres domésticos etc.) por motivo da própria saúde',
 'Algum médico já deu o diagnóstico de alguma doença crônica, física ou mental, ou doença de longa duração (de mais de 6 meses de duração) a ___',
 'Alguma dessas doenças limita de alguma forma suas atividades habituais (trabalhar, ir à escola, brincar, afazeres domésticos, etc.)',
 ' ___ costuma procurar o mesmo lugar, mesmo médico ou mesmo serviço de saúde quando precisa de atendimento de saúde',
 'Quando está doente ou precisando de atendimento de saúde___ costuma procurar',
 'Quando ____ consultou um médico pela última vez',
 'Quando ___ consultou um dentista pela última vez',
 'Nas duas últimas semanas, ___ procurou algum lugar, serviço ou profissional de saúde para atendimento relacionado à própria saúde',
 'Em geral, como o(a) Sr(a) avalia a sua saúde',
 'Peso - Informado (em kg)\n(3 inteiros e 1 casa decimal)',
 'Altura - Informada (em cm)\n(3 inteiros)',
 'Em quantos dias da semana o(a) Sr(a) costuma comer feijão? ',
 'Em quantos dias da semana, o(a) Sr(a) costuma comer pelo menos um tipo de verdura ou legume (sem contar batata, mandioca, cará ou inhame) como alface, tomate, couve, cenoura, chuchu, berinjela, abobrinha? ',
 'Em quantos dias da semana o(a) Sr(a) costuma comer carne vermelha (boi, porco, cabrito, bode, ovelha etc.)? ',
 'Em quantos dias da semana o(a) Sr(a) costuma comer frango/galinha? ',
 'Em quantos dias da semana o(a) Sr(a) costuma comer peixe? ',
 'Em quantos dias da semana o(a) Sr(a) costuma tomar refrigerante? ',
 'Em quantos dias da semana o(a) Sr(a) costuma tomar suco de caixinha/lata ou refresco em pó ? ',
 'Em quantos dias da semana o(a) Sr(a) costuma tomar suco de fruta natural (incluída a polpa de fruta congelada)? ',
 'Em quantos dias da semana o(a) Sr(a) costuma comer frutas? ',
 'Em quantos dias da semana o(a) Sr(a) costuma tomar leite? (de origem animal: vaca, cabra, búfala etc.) ',
 'Que tipo de leite o(a) Sr(a) costuma tomar? ',
 'Em quantos dias da semana o(a) Sr(a) costuma comer alimentos doces como biscoito/bolacha recheado, chocolate, gelatina, balas e outros?',
 'Em quantos dias da semana o(a) Sr(a) costuma substituir a refeição do almoço por lanches rápidos como sanduíches, salgados, pizza, cachorro quente, etc? ',
 'Considerando a comida preparada na hora e os alimentos industrializados, o(a) Sr(a) acha que o seu consumo de sal é:',
 'Nos últimos três meses, o(a) Sr(a) praticou algum tipo de exercício físico ou esporte? ',
 'Com que frequência o(a) Sr(a) costuma consumir alguma bebida alcoólica?',
 'Algum médico já lhe deu o diagnóstico de hipertensão arterial (pressão alta)? ',
 'Algum médico já lhe deu o diagnóstico de diabetes? ',
 'Quando foi a última vez que o(a) Sr(a) fez exame de sangue para medir a glicemia, isto é, o açúcar no sangue? ']

In [32]:
col = "Em geral, como o(a) Sr(a) avalia a sua saúde"
cols = list(df_filter.columns)
cols.remove(col)
cols.insert(1, col)
df_filter = df_filter[cols]
df_filter.head(5)

,Unidade da Federação,"Em geral, como o(a) Sr(a) avalia a sua saúde",Sexo,Idade do morador na data de referência,Cor ou raça,Qual é o estado civil de ___?,Sabe ler e escrever,Frequenta escola ou creche,Qual foi o curso mais elevado que ___frequentou,___concluiu este curso que frequentou,...,"Em quantos dias da semana o(a) Sr(a) costuma tomar leite? (de origem animal: vaca, cabra, búfala etc.)",Que tipo de leite o(a) Sr(a) costuma tomar?,"Em quantos dias da semana o(a) Sr(a) costuma comer alimentos doces como biscoito/bolacha recheado, chocolate, gelatina, balas e outros?","Em quantos dias da semana o(a) Sr(a) costuma substituir a refeição do almoço por lanches rápidos como sanduíches, salgados, pizza, cachorro quente, etc?","Considerando a comida preparada na hora e os alimentos industrializados, o(a) Sr(a) acha que o seu consumo de sal é:","Nos últimos três meses, o(a) Sr(a) praticou algum tipo de exercício físico ou esporte?",Com que frequência o(a) Sr(a) costuma consumir alguma bebida alcoólica?,Algum médico já lhe deu o diagnóstico de hipertensão arterial (pressão alta)?,Algum médico já lhe deu o diagnóstico de diabetes?,"Quando foi a última vez que o(a) Sr(a) fez exame de sangue para medir a glicemia, isto é, o açúcar no sangue?"
0,11,3,2,055,1,1,1,2,05,1,...,7,2,0,0,3,1,2,1,2,1
1,11,NaN,1,069,4,1,1,2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11,NaN,1,031,2,4,1,2,10,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,11,NaN,1,009,2,NaN,1,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11,NaN,2,006,4,NaN,1,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
len(df_filter.columns)

44

In [34]:
print(df_filter.columns.tolist())

['Unidade da Federação', 'Em geral, como o(a) Sr(a) avalia a sua saúde', 'Sexo', 'Idade do morador na data de referência', 'Cor ou raça', 'Qual é o estado civil de ___? ', 'Sabe ler e escrever', 'Frequenta escola ou creche', 'Qual foi o curso mais elevado que ___frequentou ', '___concluiu este curso que frequentou ', 'Em (mês da pesquisa) ___ recebia normalmente rendimento de aposentadoria ou pensão de instituto de previdência federal (INSS), estadual, municipal, ou do governo federal, estadual, municipal?', 'Em (mês da pesquisa), ___ recebia normalmente rendimento de pensão alimentícia, doação ou mesada em dinheiro de pessoa que não morava no domicílio?', 'Em (mês da pesquisa), ___ recebia normalmente rendimento de aluguel ou arrendamento?', 'tem algum plano odontológico particular, de empresa ou órgão público?', 'tem algum plano de saúde médico particular, de empresa ou órgão público?', ' Nas duas últimas semanas, ___ deixou de realizar quaisquer de suas atividades habituais (trabalhar, ir à escola, brincar, afazeres domésticos etc.) por motivo da própria saúde', 'Algum médico já deu o diagnóstico de alguma doença crônica, física ou mental, ou doença de longa duração (de mais de 6 meses de duração) a ___', 'Alguma dessas doenças limita de alguma forma suas atividades habituais (trabalhar, ir à escola, brincar, afazeres domésticos, etc.)', ' ___ costuma procurar o mesmo lugar, mesmo médico ou mesmo serviço de saúde quando precisa de atendimento de saúde', 'Quando está doente ou precisando de atendimento de saúde___ costuma procurar', 'Quando ____ consultou um médico pela última vez', 'Quando ___ consultou um dentista pela última vez', 'Nas duas últimas semanas, ___ procurou algum lugar, serviço ou profissional de saúde para atendimento relacionado à própria saúde', 'Peso - Informado (em kg)\n(3 inteiros e 1 casa decimal)', 'Altura - Informada (em cm)\n(3 inteiros)', 'Em quantos dias da semana o(a) Sr(a) costuma comer feijão? ', 'Em quantos dias da semana, o(a) Sr(a) costuma comer pelo menos um tipo de verdura ou legume (sem contar batata, mandioca, cará ou inhame) como alface, tomate, couve, cenoura, chuchu, berinjela, abobrinha? ', 'Em quantos dias da semana o(a) Sr(a) costuma comer carne vermelha (boi, porco, cabrito, bode, ovelha etc.)? ', 'Em quantos dias da semana o(a) Sr(a) costuma comer frango/galinha? ', 'Em quantos dias da semana o(a) Sr(a) costuma comer peixe? ', 'Em quantos dias da semana o(a) Sr(a) costuma tomar refrigerante? ', 'Em quantos dias da semana o(a) Sr(a) costuma tomar suco de caixinha/lata ou refresco em pó ? ', 'Em quantos dias da semana o(a) Sr(a) costuma tomar suco de fruta natural (incluída a polpa de fruta congelada)? ', 'Em quantos dias da semana o(a) Sr(a) costuma comer frutas? ', 'Em quantos dias da semana o(a) Sr(a) costuma tomar leite? (de origem animal: vaca, cabra, búfala etc.) ', 'Que tipo de leite o(a) Sr(a) costuma tomar? ', 'Em quantos dias da semana o(a) Sr(a) costuma comer alimentos doces como biscoito/bolacha recheado, chocolate, gelatina, balas e outros?', 'Em quantos dias da semana o(a) Sr(a) costuma substituir a refeição do almoço por lanches rápidos como sanduíches, salgados, pizza, cachorro quente, etc? ', 'Considerando a comida preparada na hora e os alimentos industrializados, o(a) Sr(a) acha que o seu consumo de sal é:', 'Nos últimos três meses, o(a) Sr(a) praticou algum tipo de exercício físico ou esporte? ', 'Com que frequência o(a) Sr(a) costuma consumir alguma bebida alcoólica?', 'Algum médico já lhe deu o diagnóstico de hipertensão arterial (pressão alta)? ', 'Algum médico já lhe deu o diagnóstico de diabetes? ', 'Quando foi a última vez que o(a) Sr(a) fez exame de sangue para medir a glicemia, isto é, o açúcar no sangue? ']

In [35]:
df_vazios = df_filter[df_filter[col].isna() | (df_filter[col].str.strip() == "")]
df_filter.shape[0] - len(df_vazios), df_filter.shape[0]

(90846, 279382)

In [36]:
col = "Em geral, como o(a) Sr(a) avalia a sua saúde"

df_90k = df_filter[~(df_filter[col].isna() | (df_filter[col].str.strip() == ""))]
df_90k

,Unidade da Federação,"Em geral, como o(a) Sr(a) avalia a sua saúde",Sexo,Idade do morador na data de referência,Cor ou raça,Qual é o estado civil de ___?,Sabe ler e escrever,Frequenta escola ou creche,Qual foi o curso mais elevado que ___frequentou,___concluiu este curso que frequentou,...,"Em quantos dias da semana o(a) Sr(a) costuma tomar leite? (de origem animal: vaca, cabra, búfala etc.)",Que tipo de leite o(a) Sr(a) costuma tomar?,"Em quantos dias da semana o(a) Sr(a) costuma comer alimentos doces como biscoito/bolacha recheado, chocolate, gelatina, balas e outros?","Em quantos dias da semana o(a) Sr(a) costuma substituir a refeição do almoço por lanches rápidos como sanduíches, salgados, pizza, cachorro quente, etc?","Considerando a comida preparada na hora e os alimentos industrializados, o(a) Sr(a) acha que o seu consumo de sal é:","Nos últimos três meses, o(a) Sr(a) praticou algum tipo de exercício físico ou esporte?",Com que frequência o(a) Sr(a) costuma consumir alguma bebida alcoólica?,Algum médico já lhe deu o diagnóstico de hipertensão arterial (pressão alta)?,Algum médico já lhe deu o diagnóstico de diabetes?,"Quando foi a última vez que o(a) Sr(a) fez exame de sangue para medir a glicemia, isto é, o açúcar no sangue?"
0,11,3,2,055,1,1,1,2,05,1,...,7,2,0,0,3,1,2,1,2,1
9,11,2,2,019,4,4,1,2,10,2,...,0,NaN,0,0,3,2,2,2,2,2
10,11,3,2,045,2,4,1,2,10,1,...,0,NaN,0,0,4,2,3,2,2,1
18,11,3,2,058,2,3,2,2,04,2,...,0,NaN,0,0,3,1,1,2,2,2
19,11,2,2,028,4,4,1,1,NaN,NaN,...,7,2,2,0,3,1,1,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
293709,53,3,2,054,4,1,1,2,10,1,...,0,NaN,0,0,4,2,3,2,2,3
293712,53,2,1,044,4,2,1,2,10,1,...,0,NaN,0,0,4,2,3,2,NaN,6
293713,53,2,2,032,4,1,1,2,07,1,...,7,2,7,0,3,1,1,2,2,5
293718,53,3,1,054,4,1,1,2,11,1,...,0,NaN,0,0,3,1,1,2,2,3
293720,53,3,1,032,1,4,1,2,07,1,...,7,2,2,0,3,1,3,2,NaN,6

In [ ]:
df_90k[df_90k["Em geral, como o(a) Sr(a) avalia a sua saúde"] == "9"]

Empty DataFrame
Columns: [Unidade da Federação, Em geral, como o(a) Sr(a) avalia a sua saúde, Sexo, Idade do morador na data de referência, Cor ou raça, Qual é o estado civil de ___?, Sabe ler e escrever, Frequenta escola ou creche, Qual foi o curso mais elevado que ___frequentou, ___concluiu este curso que frequentou, Em (mês da pesquisa) ___ recebia normalmente rendimento de aposentadoria ou pensão de instituto de previdência federal (INSS), estadual, municipal, ou do governo federal, estadual, municipal?, Em (mês da pesquisa), ___ recebia normalmente rendimento de pensão alimentícia, doação ou mesada em dinheiro de pessoa que não morava no domicílio?, Em (mês da pesquisa), ___ recebia normalmente rendimento de aluguel ou arrendamento?, tem algum plano odontológico particular, de empresa ou órgão público?, tem algum plano de saúde médico particular, de empresa ou órgão público?, Nas duas últimas semanas, ___ deixou de realizar quaisquer de suas atividades habituais (trabalhar, ir à escola, brincar, afazeres domésticos etc.) por motivo da própria saúde, Algum médico já deu o diagnóstico de alguma doença crônica, física ou mental, ou doença de longa duração (de mais de 6 meses de duração) a ___, Alguma dessas doenças limita de alguma forma suas atividades habituais (trabalhar, ir à escola, brincar, afazeres domésticos, etc.), ___ costuma procurar o mesmo lugar, mesmo médico ou mesmo serviço de saúde quando precisa de atendimento de saúde, Quando está doente ou precisando de atendimento de saúde___ costuma procurar, Quando ____ consultou um médico pela última vez, Quando ___ consultou um dentista pela última vez, Nas duas últimas semanas, ___ procurou algum lugar, serviço ou profissional de saúde para atendimento relacionado à própria saúde, Peso - Informado (em kg)
(3 inteiros e 1 casa decimal), Altura - Informada (em cm)
(3 inteiros), Em quantos dias da semana o(a) Sr(a) costuma comer feijão?, Em quantos dias da semana, o(a) Sr(a) costuma comer pelo menos um tipo de verdura ou legume (sem contar batata, mandioca, cará ou inhame) como alface, tomate, couve, cenoura, chuchu, berinjela, abobrinha?, Em quantos dias da semana o(a) Sr(a) costuma comer carne vermelha (boi, porco, cabrito, bode, ovelha etc.)?, Em quantos dias da semana o(a) Sr(a) costuma comer frango/galinha?, Em quantos dias da semana o(a) Sr(a) costuma comer peixe?, Em quantos dias da semana o(a) Sr(a) costuma tomar refrigerante?, Em quantos dias da semana o(a) Sr(a) costuma tomar suco de caixinha/lata ou refresco em pó ?, Em quantos dias da semana o(a) Sr(a) costuma tomar suco de fruta natural (incluída a polpa de fruta congelada)?, Em quantos dias da semana o(a) Sr(a) costuma comer frutas?, Em quantos dias da semana o(a) Sr(a) costuma tomar leite? (de origem animal: vaca, cabra, búfala etc.), Que tipo de leite o(a) Sr(a) costuma tomar?, Em quantos dias da semana o(a) Sr(a) costuma comer alimentos doces como biscoito/bolacha recheado, chocolate, gelatina, balas e outros?, Em quantos dias da semana o(a) Sr(a) costuma substituir a refeição do almoço por lanches rápidos como sanduíches, salgados, pizza, cachorro quente, etc?, Considerando a comida preparada na hora e os alimentos industrializados, o(a) Sr(a) acha que o seu consumo de sal é:, Nos últimos três meses, o(a) Sr(a) praticou algum tipo de exercício físico ou esporte?, Com que frequência o(a) Sr(a) costuma consumir alguma bebida alcoólica?, Algum médico já lhe deu o diagnóstico de hipertensão arterial (pressão alta)?, Algum médico já lhe deu o diagnóstico de diabetes?, Quando foi a última vez que o(a) Sr(a) fez exame de sangue para medir a glicemia, isto é, o açúcar no sangue?]
Index: []

[0 rows x 44 columns]

In [37]:
df_filter.to_csv("./data/df_filter_my_variables.csv", index=False, encoding="utf-8")

In [38]:
df_90k.to_csv("./data/df_filter_90k.csv", index=False, encoding="utf-8")

In [39]:
df_90k.head()

,Unidade da Federação,"Em geral, como o(a) Sr(a) avalia a sua saúde",Sexo,Idade do morador na data de referência,Cor ou raça,Qual é o estado civil de ___?,Sabe ler e escrever,Frequenta escola ou creche,Qual foi o curso mais elevado que ___frequentou,___concluiu este curso que frequentou,...,"Em quantos dias da semana o(a) Sr(a) costuma tomar leite? (de origem animal: vaca, cabra, búfala etc.)",Que tipo de leite o(a) Sr(a) costuma tomar?,"Em quantos dias da semana o(a) Sr(a) costuma comer alimentos doces como biscoito/bolacha recheado, chocolate, gelatina, balas e outros?","Em quantos dias da semana o(a) Sr(a) costuma substituir a refeição do almoço por lanches rápidos como sanduíches, salgados, pizza, cachorro quente, etc?","Considerando a comida preparada na hora e os alimentos industrializados, o(a) Sr(a) acha que o seu consumo de sal é:","Nos últimos três meses, o(a) Sr(a) praticou algum tipo de exercício físico ou esporte?",Com que frequência o(a) Sr(a) costuma consumir alguma bebida alcoólica?,Algum médico já lhe deu o diagnóstico de hipertensão arterial (pressão alta)?,Algum médico já lhe deu o diagnóstico de diabetes?,"Quando foi a última vez que o(a) Sr(a) fez exame de sangue para medir a glicemia, isto é, o açúcar no sangue?"
0,11,3,2,055,1,1,1,2,05,1,...,7,2,0,0,3,1,2,1,2,1
9,11,2,2,019,4,4,1,2,10,2,...,0,NaN,0,0,3,2,2,2,2,2
10,11,3,2,045,2,4,1,2,10,1,...,0,NaN,0,0,4,2,3,2,2,1
18,11,3,2,058,2,3,2,2,04,2,...,0,NaN,0,0,3,1,1,2,2,2
19,11,2,2,028,4,4,1,1,NaN,NaN,...,7,2,2,0,3,1,1,2,2,2

In [40]:
list(df_filter.columns)

['Unidade da Federação',
 'Em geral, como o(a) Sr(a) avalia a sua saúde',
 'Sexo',
 'Idade do morador na data de referência',
 'Cor ou raça',
 'Qual é o estado civil de ___? ',
 'Sabe ler e escrever',
 'Frequenta escola ou creche',
 'Qual foi o curso mais elevado que ___frequentou ',
 '___concluiu este curso que frequentou ',
 'Em (mês da pesquisa) ___ recebia normalmente rendimento de aposentadoria ou pensão de instituto de previdência federal (INSS), estadual, municipal, ou do governo federal, estadual, municipal?',
 'Em (mês da pesquisa), ___ recebia normalmente rendimento de pensão alimentícia, doação ou mesada em dinheiro de pessoa que não morava no domicílio?',
 'Em (mês da pesquisa), ___ recebia normalmente rendimento de aluguel ou arrendamento?',
 'tem algum plano odontológico particular, de empresa ou órgão público?',
 'tem algum plano de saúde médico particular, de empresa ou órgão público?',
 ' Nas duas últimas semanas, ___ deixou de realizar quaisquer de suas atividades habituais (trabalhar, ir à escola, brincar, afazeres domésticos etc.) por motivo da própria saúde',
 'Algum médico já deu o diagnóstico de alguma doença crônica, física ou mental, ou doença de longa duração (de mais de 6 meses de duração) a ___',
 'Alguma dessas doenças limita de alguma forma suas atividades habituais (trabalhar, ir à escola, brincar, afazeres domésticos, etc.)',
 ' ___ costuma procurar o mesmo lugar, mesmo médico ou mesmo serviço de saúde quando precisa de atendimento de saúde',
 'Quando está doente ou precisando de atendimento de saúde___ costuma procurar',
 'Quando ____ consultou um médico pela última vez',
 'Quando ___ consultou um dentista pela última vez',
 'Nas duas últimas semanas, ___ procurou algum lugar, serviço ou profissional de saúde para atendimento relacionado à própria saúde',
 'Peso - Informado (em kg)\n(3 inteiros e 1 casa decimal)',
 'Altura - Informada (em cm)\n(3 inteiros)',
 'Em quantos dias da semana o(a) Sr(a) costuma comer feijão? ',
 'Em quantos dias da semana, o(a) Sr(a) costuma comer pelo menos um tipo de verdura ou legume (sem contar batata, mandioca, cará ou inhame) como alface, tomate, couve, cenoura, chuchu, berinjela, abobrinha? ',
 'Em quantos dias da semana o(a) Sr(a) costuma comer carne vermelha (boi, porco, cabrito, bode, ovelha etc.)? ',
 'Em quantos dias da semana o(a) Sr(a) costuma comer frango/galinha? ',
 'Em quantos dias da semana o(a) Sr(a) costuma comer peixe? ',
 'Em quantos dias da semana o(a) Sr(a) costuma tomar refrigerante? ',
 'Em quantos dias da semana o(a) Sr(a) costuma tomar suco de caixinha/lata ou refresco em pó ? ',
 'Em quantos dias da semana o(a) Sr(a) costuma tomar suco de fruta natural (incluída a polpa de fruta congelada)? ',
 'Em quantos dias da semana o(a) Sr(a) costuma comer frutas? ',
 'Em quantos dias da semana o(a) Sr(a) costuma tomar leite? (de origem animal: vaca, cabra, búfala etc.) ',
 'Que tipo de leite o(a) Sr(a) costuma tomar? ',
 'Em quantos dias da semana o(a) Sr(a) costuma comer alimentos doces como biscoito/bolacha recheado, chocolate, gelatina, balas e outros?',
 'Em quantos dias da semana o(a) Sr(a) costuma substituir a refeição do almoço por lanches rápidos como sanduíches, salgados, pizza, cachorro quente, etc? ',
 'Considerando a comida preparada na hora e os alimentos industrializados, o(a) Sr(a) acha que o seu consumo de sal é:',
 'Nos últimos três meses, o(a) Sr(a) praticou algum tipo de exercício físico ou esporte? ',
 'Com que frequência o(a) Sr(a) costuma consumir alguma bebida alcoólica?',
 'Algum médico já lhe deu o diagnóstico de hipertensão arterial (pressão alta)? ',
 'Algum médico já lhe deu o diagnóstico de diabetes? ',
 'Quando foi a última vez que o(a) Sr(a) fez exame de sangue para medir a glicemia, isto é, o açúcar no sangue? ']

In [60]:
df_name = df_90k



df_name.columns = df_name.columns.str.strip()
lista_sem_nulos = []
for col in df_name.columns:
    num_nulos = df_name[col].isna().sum()
    if num_nulos == 0:
        # print(col)
        lista_sem_nulos.append(col)
print(len(lista_sem_nulos))

35

In [61]:
import pandas as pd
cols_ausentes = {}
cols_ausentes_list = []
def contar_nulos(df: pd.DataFrame):
    nulos = df.isnull().sum()
    nulos = nulos[nulos > 0]
    return nulos.to_dict()


dff = pd.read_csv("./data/df_filter_90k.csv")
nulos_por_coluna = contar_nulos(dff)

for coluna, n_nulos in nulos_por_coluna.items():
    # print(f"{coluna}: {n_nulos} valores nulos")
    cols_ausentes_list.append(coluna)
    cols_ausentes[coluna] = n_nulos
    
ordenado_decrescente = dict(sorted(cols_ausentes.items(), key=lambda item: item[1], reverse=True))
print(ordenado_decrescente)

{'Alguma dessas doenças limita de alguma forma suas atividades habituais (trabalhar, ir à escola, brincar, afazeres domésticos, etc.)': 43397, 'Que tipo de leite o(a) Sr(a) costuma tomar? ': 27742, 'Quando está doente ou precisando de atendimento de saúde___ costuma procurar': 23335, '___concluiu este curso que frequentou ': 16647, 'Altura - Informada (em cm)\n(3 inteiros)': 15209, 'Qual foi o curso mais elevado que ___frequentou ': 13965, 'Peso - Informado (em kg)\n(3 inteiros e 1 casa decimal)': 7773, 'Algum médico já lhe deu o diagnóstico de diabetes? ': 6773, 'Algum médico já lhe deu o diagnóstico de hipertensão arterial (pressão alta)? ': 2110}

In [62]:
for each in ordenado_decrescente:
  print(each)

Alguma dessas doenças limita de alguma forma suas atividades habituais (trabalhar, ir à escola, brincar, afazeres domésticos, etc.)
Que tipo de leite o(a) Sr(a) costuma tomar?
Quando está doente ou precisando de atendimento de saúde___ costuma procurar
___concluiu este curso que frequentou
Altura - Informada (em cm)
(3 inteiros)
Qual foi o curso mais elevado que ___frequentou
Peso - Informado (em kg)
(3 inteiros e 1 casa decimal)
Algum médico já lhe deu o diagnóstico de diabetes?
Algum médico já lhe deu o diagnóstico de hipertensão arterial (pressão alta)?

In [55]:
dff.drop(columns=cols_ausentes_list)

,Unidade da Federação,"Em geral, como o(a) Sr(a) avalia a sua saúde",Sexo,Idade do morador na data de referência,Cor ou raça,Qual é o estado civil de ___?,Sabe ler e escrever,Frequenta escola ou creche,"Em (mês da pesquisa) ___ recebia normalmente rendimento de aposentadoria ou pensão de instituto de previdência federal (INSS), estadual, municipal, ou do governo federal, estadual, municipal?","Em (mês da pesquisa), ___ recebia normalmente rendimento de pensão alimentícia, doação ou mesada em dinheiro de pessoa que não morava no domicílio?",...,Em quantos dias da semana o(a) Sr(a) costuma tomar suco de caixinha/lata ou refresco em pó ?,Em quantos dias da semana o(a) Sr(a) costuma tomar suco de fruta natural (incluída a polpa de fruta congelada)?,Em quantos dias da semana o(a) Sr(a) costuma comer frutas?,"Em quantos dias da semana o(a) Sr(a) costuma tomar leite? (de origem animal: vaca, cabra, búfala etc.)","Em quantos dias da semana o(a) Sr(a) costuma comer alimentos doces como biscoito/bolacha recheado, chocolate, gelatina, balas e outros?","Em quantos dias da semana o(a) Sr(a) costuma substituir a refeição do almoço por lanches rápidos como sanduíches, salgados, pizza, cachorro quente, etc?","Considerando a comida preparada na hora e os alimentos industrializados, o(a) Sr(a) acha que o seu consumo de sal é:","Nos últimos três meses, o(a) Sr(a) praticou algum tipo de exercício físico ou esporte?",Com que frequência o(a) Sr(a) costuma consumir alguma bebida alcoólica?,"Quando foi a última vez que o(a) Sr(a) fez exame de sangue para medir a glicemia, isto é, o açúcar no sangue?"
0,11,3,2,55,1,1,1,2,2,2,...,7,0,3,7,0,0,3,1,2,1
1,11,2,2,19,4,4,1,2,2,2,...,0,0,0,0,0,0,3,2,2,2
2,11,3,2,45,2,4,1,2,2,2,...,0,7,7,0,0,0,4,2,3,1
3,11,3,2,58,2,3,2,2,2,2,...,0,3,3,0,0,0,3,1,1,2
4,11,2,2,28,4,4,1,1,2,2,...,2,4,3,7,2,0,3,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90841,53,3,2,54,4,1,1,2,2,2,...,0,7,2,0,0,0,4,2,3,3
90842,53,2,1,44,4,2,1,2,2,2,...,0,2,3,0,0,0,4,2,3,6
90843,53,2,2,32,4,1,1,2,2,2,...,0,0,1,7,7,0,3,1,1,5
90844,53,3,1,54,4,1,1,2,1,2,...,0,4,3,0,0,0,3,1,1,3
90845,53,3,1,32,1,4,1,2,2,2,...,4,0,5,7,2,0,3,1,3,6